version: '3.8'

# 网桥 -> 方便相互通讯
networks:
  rocketmq:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"

services:
  namesrv:
    image: registry.cn-shanghai.aliyuncs.com/odboy/apache-rocketmq:4.9.6
    container_name: rmqnamesrv
    ports:
      - "9876:9876"
    networks:
      rocketmq:
        ipv4_address: 172.20.0.80
    command: sh mqnamesrv
  broker1:
    image: registry.cn-shanghai.aliyuncs.com/odboy/apache-rocketmq:4.9.6
    container_name: rmqbroker1
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ./broker-master/broker.conf:/home/rocketmq/rocketmq-4.9.6/conf/broker.conf
    depends_on:
      - namesrv
    networks:
      rocketmq:
        ipv4_address: 172.20.0.81
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.6/conf/broker.conf
  broker2:
    image: registry.cn-shanghai.aliyuncs.com/odboy/apache-rocketmq:4.9.6
    container_name: rmqbroker2
    ports:
      - "10809:10909"
      - "10811:10911"
      - "10812:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ./broker-slave1/broker.conf:/home/rocketmq/rocketmq-4.9.6/conf/broker.conf
    depends_on:
      - namesrv
    networks:
      rocketmq:
        ipv4_address: 172.20.0.82
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.6/conf/broker.conf
  broker3:
    image: registry.cn-shanghai.aliyuncs.com/odboy/apache-rocketmq:4.9.6
    container_name: rmqbroker3
    ports:
      - "10709:10909"
      - "10711:10911"
      - "10712:10912"
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    volumes:
      - ./broker-slave2/broker.conf:/home/rocketmq/rocketmq-4.9.6/conf/broker.conf
    depends_on:
      - namesrv
    networks:
      rocketmq:
        ipv4_address: 172.20.0.83
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.6/conf/broker.conf
  rmqdashboard:
    image: registry.cn-shanghai.aliyuncs.com/odboy/rocketmq-dashboard:latest
    container_name: rocketmq-dashboard
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - namesrv
    networks:
      rocketmq:
        ipv4_address: 172.20.0.84
    environment:
      - JAVA_OPTS= -Xms256M -Xms512M -Xmn128M -Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false

