# 可参考 https://github.com/apache/skywalking/blob/master/docker/docker-compose.yml
version: '3.8'

# 网桥 -> 方便相互通讯
networks:
  skywalking:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/24"

services:
  mysql:
    image: registry.cn-shanghai.aliyuncs.com/odboy/mysql:8.0  # 原镜像`mysql:8.0`
    container_name: mysql8                                    # 容器名为'mysql8'
    restart: unless-stopped
    volumes: # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/data:/var/lib/mysql"
      #      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "./mysql/mysql-files:/var/lib/mysql-files"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
      MYSQL_DATABASE: skywalking              # 初始化的数据库名称
    privileged: true
    user: root
    ports: # 映射端口
      - "3308:3306"
    networks:
      skywalking:
        ipv4_address: 172.24.0.80
  oap:
    image: registry.cn-shanghai.aliyuncs.com/odboy/skywalking-oap-server:9.5.0 # 原镜像`apache/skywalking-oap-server:9.5.0`
    container_name: oap
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xmx2048M -Xms2048M"
      SW_STORAGE: mysql
      # tips: 需等待自动创建60张表...
      SW_JDBC_URL: "jdbc:mysql://172.24.0.80:3306/skywalking?rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false"
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: root
    volumes:
      # 驱动 https://mvnrepository.com/artifact/com.mysql/mysql-connector-j/9.2.0
      - "./skywalking/mysql-connector-j-9.2.0.jar:/skywalking/ext-libs/mysql-connector-j-9.2.0.jar"
    ports:
      - "11800:11800" # agent 上报数据的端口，这是 gRPC 端口
      - "12800:12800" # ui 读取数据的端口， 这是 http 端口
    networks:
      skywalking:
        ipv4_address: 172.24.0.81

  # 可视化界面
  oap-ui:
    image: registry.cn-shanghai.aliyuncs.com/odboy/skywalking-ui:9.5.0 # 原镜像`apache/skywalking-ui:9.5.0`
    container_name: oap-ui
    restart: unless-stopped
    depends_on:
      - oap
    links:
      - oap
    ports:
      - "18080:8080"
    environment:
      TZ: Asia/Shanghai
      SW_SERVER_PORT: 8080                     # 设置SkyWalking UI的监听端口
      SW_OAP_ADDRESS: http://172.24.0.81:12800 # SkyWalking OAP服务器的地址和端口
    networks:
      skywalking:
        ipv4_address: 172.24.0.82
